server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Proxy inverso interno hacia el backend dentro del cluster GKE
    # El DNS interno de Kubernetes resuelve: <service>.<namespace>.svc.cluster.local
    # NOTA: el estudiante debe ajustar el namespace (examen-APELLIDO) en el script de setup
    location /api/ {
        proxy_pass         http://backend-api-svc.NAMESPACE_PLACEHOLDER.svc.cluster.local/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout    10s;
    }
}
