# ============================================================
#  EXAMEN FINAL — Cloud Computing | Universidad Da Vinci GT
#  Archivo: k8s/config/secret.yaml
#  Descripcion: Secret con datos sensibles (API Key)
#
#  NOTA PEDAGOGICA:
#  Los Secrets en Kubernetes almacenan los valores en Base64.
#  Base64 NO es cifrado — es solo codificacion. En produccion
#  real se usaria: Sealed Secrets, GCP Secret Manager, o
#  External Secrets Operator para cifrado real en reposo.
#
#  El valor 'api_key' abajo es Base64 de: ExamenGKE-2025-Demo
#  Para generar tu propio valor:
#    echo -n 'MiClaveSecreta' | base64
#  Para decodificar:
#    echo 'RXhhbWVuR0tFLTIwMjUtRGVtbw==' | base64 --decode
#
#  INSTRUCCION: El script setup.sh genera un valor unico
#  por estudiante automaticamente. No uses este archivo
#  directamente — deja que setup.sh lo aplique.
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    examen: cloud-computing
type: Opaque
data:
  # Base64 de: ExamenGKE-2025-Demo  (valor de ejemplo, setup.sh lo sobreescribe)
  api_key: RXhhbWVuR0tFLTIwMjUtRGVtbw==
